language: node_js

node_js:
  - 10

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run build
  - npm run coverage

after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"